### PR TITLE
Add more logging

### PR DESCRIPTION
**Pull request by hannobraun**

### CODE REVIEW

**Review by Yatekii — APPROVED** [review]
LGTM, thanks!

**Comment by mvirkkunen** [comment]
The first `debug!` is going to log almost one message per byte of RAM memory on the target when scanning through the entire RAM. That's a lot of messages, is it really necessary?

**Comment by Yatekii** [comment]
Which one exactly? I cannot see where there is a problem :/ I believe you mean with scanning RAM, but I cannot see where ...

**Comment by hannobraun** [comment]
The only code path that I actually ran is through `ScanRegion::exact`, so I can't rule out that any of the other log messages are doing something wrong. But I don't see a problem either.

**Comment by hannobraun** [comment]
Ah, I see it now. When scanning through RAM, `Rtt::attach_region` calls `Rtt::from` for every single address scanned, and that's going to run into that log message every time: https://github.com/probe-rs/probe-rs-rtt/blob/b35a7563d883f2b6913a4ca2e81ba3d7507e8e2d/probe-rs-rtt/src/rtt.rs#L69-L71

That message is still useful for the `ScanRegion::Exact` path though. Maybe downgrade it to trace level?

**Comment by Yatekii** [comment]
> That message is still useful for the `ScanRegion::Exact` path though. Maybe downgrade it to trace level?

That sounds good to me. What does @mvirkkunen think? :)

**Comment by hannobraun** [comment]
Opened #11.

**Pull request merged**
