### PR TITLE
Prepare for 0.5.0 release

### PR DESCRIPTION
**Pull request by Yatekii**

### CODE REVIEW

**Review by Tiwalun — DISMISSED** [review]
bors r+

**Review by Tiwalun — DISMISSED** [review]
bors r+

**Comment by Yatekii** [comment]
bors retry

**Comment by Yatekii** [comment]
bors abort

**Comment by Yatekii** [comment]
bors retry

**Comment by Yatekii** [comment]
bors cancel

**Review by adamgreig — APPROVED** [review]
bors r+

**Comment by Yatekii** [comment]
bors retry

**Comment by Yatekii** [comment]
bors status

**Comment by Yatekii** [comment]
bors ping

**Comment by Yatekii** [comment]
bors cancel

**Comment by Yatekii** [comment]
bors retry

**Pull request merged**
