### PR TITLE
Fix compilation after update to probe-rs 0.11.0

### PR DESCRIPTION
**Pull request by rmsc**

### CODE REVIEW

**Review by Yatekii — DISMISSED** [review]
Thank you!

bors r+

**Review by Yatekii — APPROVED** [review]

**Comment by Yatekii** [comment]
bors retry

**Comment by rmsc** [comment]
> thread 'main' panicked at 'Unable to find libudev: ...'

Not much I can do about that :)

**Comment by Yatekii** [comment]
This is odd :/ I will see what I can do. sometimes apt servers/cache is messed up for a while. will try in a bit!

**Comment by Yatekii** [comment]
I embedded your changes in the merge PR of the probe-rs-repo into the probe-rs repo. That way I do not have to fix the CI here. I hope thats ok.

https://github.com/probe-rs/probe-rs/pull/785 for reference.

**Pull request closed without merging**
